services:
  ldes-client:
    image: semtech/mu-javascript-template:1.8.0
    #build: ./
    restart: 'no'
    labels:
      - 'logging=true'
    environment:
      - NODE_ENV=development
      - NO_BABEL_NODE=true
      - LOG_LEVEL=debug
      - TARGET_GRAPH=http://mu.semte.ch/graphs/test/ldes-target
      - BATCH_SIZE=500
      - BYPASS_MU_AUTH=false
      - LDES_BASE=http://ldes-backend/public/
      - FIRST_PAGE=http://ldes-backend/public/1
    ports:
      - '8081:80'
      - '9224:9229'
    volumes:
      - ../app-lokaal-mandatenbeheer/config/ldes-client:/config
      - ./:/app
      # ignore app/dist because this is where we map the built files to, otherwise we get an infinite loop of creating files (on mac)
      - /app/dist
      - ./dist:/build/
    networks:
      - debug
networks:
  debug:
    external: true
  deltas-sync:
    external: true
